spring:
  application:
    name: character
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/character_db
    username: postgres
    password: postgres

feign:
  url:
    starwars: https://swapi.dev/api